version: '3'

volumes:
  prometheus-data:
    driver: local
  grafana-data:
    driver: local

services:
  prometheus:
    image: prom/prometheus:latest
#    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - /vagrant/config/prometheus/etc/prometheus.yml:/etc/prometheus/prometheus.yml
#      - /vagrant/config/prometheus/etc:/etc/prometheus
      - prometheus-data:/prometheus
#    command:
#      - "--config.file=/vagrant/config/prometheus/prometheus.yml"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname == worker01

  grafana:
    image: grafana/grafana:latest
#    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    deploy:
      mode: replicated
      replicas: 2
      placement:
        constraints:
          - node.hostname == worker02

  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
#    container_name: node_exporter
    command:
      - '--path.rootfs=/host'
    pid: host
    volumes:
      - '/:/host:ro,rslave'
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname == worker01

  cadvisor:
    image: google/cadvisor:latest
#    container_name: cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    devices:
      - /dev/kmsg
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname == worker02